{"name": "Проверка отображения ошибки при попытке сохранить обращение без заполненных данных", "status": "passed", "steps": [{"name": "Выделяется заявка номер: \"6\"", "status": "passed", "parameters": [{"name": "number", "value": "6"}], "start": 1579873976985, "stop": 1579873977941}, {"name": "Клик на кнопку \"Завершить назначение\"", "status": "passed", "start": 1579873977942, "stop": 1579873978237}, {"name": "Проверка отображения ошибки при завершении обращения", "status": "passed", "start": 1579873978237, "stop": 1579873978321}], "attachments": [{"name": "log", "source": "403df684-b4c8-481b-9f8d-780e713922e9-attachment.txt", "type": "text/plain"}], "start": 1579873975604, "stop": 1579873978321, "uuid": "f4f2dbb2-d1f9-4683-84c2-bd88866d4178", "historyId": "98fd29f41e09050c3aea8c5126d36298", "testCaseId": "a31d7eba551ff8eb852ec8892552bb44", "fullName": "tests.test_do.TestUI#test_error_save_appointment_without_data", "labels": [{"name": "severity", "value": "normal"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_do"}, {"name": "subSuite", "value": "TestUI"}, {"name": "host", "value": "iMac-1.local"}, {"name": "thread", "value": "32001-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_do"}]}