{"name": "Verify error display if try logout with open requests", "status": "passed", "description": "Проверка отображения ошибки при попытке выйти из аккаунта с не завершенными обращениями.", "steps": [{"name": "Выход из аккаунта", "status": "passed", "start": 1579866334580, "stop": 1579866335665}, {"name": "Ошибка выхода отображается", "status": "passed", "start": 1579866335665, "stop": 1579866335773}], "attachments": [{"name": "log", "source": "37420981-a3fa-4d14-8be8-85f62125b30f-attachment.txt", "type": "text/plain"}], "start": 1579866332968, "stop": 1579866335773, "uuid": "e7d35aea-52a1-4e12-abc5-027fc276c310", "historyId": "f2b48e3cb26117a0e9d6c1f459ef4107", "testCaseId": "bb21e8809bc5a8397036e82874be701d", "fullName": "tests.test_do.TestUI#test_error_logout_with_requests", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_do"}, {"name": "subSuite", "value": "TestUI"}, {"name": "host", "value": "iMac-1.local"}, {"name": "thread", "value": "27895-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_do"}]}