{"name": "Проверка отображения ошибки при попытке выйти из аккаунта с не завершенными обращениями", "status": "passed", "steps": [{"name": "Выход из аккаунта", "status": "passed", "start": 1579873979678, "stop": 1579873980650}, {"name": "Проверка отображения ошибки при выходе", "status": "passed", "start": 1579873980651, "stop": 1579873980713}], "attachments": [{"name": "log", "source": "6e022622-73fd-4de6-8341-d8a6fc89115e-attachment.txt", "type": "text/plain"}], "start": 1579873978329, "stop": 1579873980713, "uuid": "3decb617-f1f8-4465-9613-e6fd2f0f0508", "historyId": "f2b48e3cb26117a0e9d6c1f459ef4107", "testCaseId": "bb21e8809bc5a8397036e82874be701d", "fullName": "tests.test_do.TestUI#test_error_logout_with_requests", "labels": [{"name": "severity", "value": "normal"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_do"}, {"name": "subSuite", "value": "TestUI"}, {"name": "host", "value": "iMac-1.local"}, {"name": "thread", "value": "32001-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_do"}]}