{"name": "Проверка отображения ошибки при попытке выйти из аккаунта с не завершенными обращениями", "status": "passed", "steps": [{"name": "Выход из аккаунта", "status": "passed", "start": 1579876292015, "stop": 1579876292735}, {"name": "Проверка отображения ошибки при выходе", "status": "passed", "start": 1579876292735, "stop": 1579876292801}], "attachments": [{"name": "log", "source": "2985789c-b740-41fa-a696-f67da7c820ef-attachment.txt", "type": "text/plain"}], "start": 1579876290393, "stop": 1579876292801, "uuid": "f23e4695-a503-4126-a7b7-35d7c0234226", "historyId": "f2b48e3cb26117a0e9d6c1f459ef4107", "testCaseId": "bb21e8809bc5a8397036e82874be701d", "fullName": "tests.test_do.TestUI#test_error_logout_with_requests", "labels": [{"name": "severity", "value": "normal"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_do"}, {"name": "subSuite", "value": "TestUI"}, {"name": "host", "value": "iMac-1.local"}, {"name": "thread", "value": "33282-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_do"}]}